### ISSUE TITLE
F_state每次提交不同

### ISSUE THREAD

**Issue by CabbageSong** [BlueFisher/SHU-selfreport#11]
同学你好，我发现自己网页提交的时候，每次F_state码都不一样，请问使用固定值是否影响报送

**Comment by BlueFisher** [comment]
@CabbageSong 我暂时也不知道F_state是怎么产生的，目前看下来固定F_state没有什么问题，过几天再看看，如果有问题再修改。

**Comment by panghaibin** [comment]
> @CabbageSong 我暂时也不知道F_state是怎么产生的，目前看下来固定F_state没有什么问题，过几天再看看，如果有问题再修改。

F_state是将json格式的要上报的信息base64 encode后得到的
另外我看代码默认是宝山区，建议加上为不同用户指定校区的功能

**Comment by BlueFisher** [comment]
> > @CabbageSong 我暂时也不知道F_state是怎么产生的，目前看下来固定F_state没有什么问题，过几天再看看，如果有问题再修改。
> 
> F_state是将json格式的要上报的信息base64 encode后得到的，base64 decode后可查看原始数据，包含了日期，体温，地址等信息，最好每次上报时都重新base64 encode生成
> 另外我看代码默认是宝山区，可以考虑加上为不同用户指定不同校区的功能

如果换成其他校区是不是F_STATE也要修改。不过话说这每日两报还管你在哪个校区吗？

**Comment by panghaibin** [comment]
@BlueFisher 
> 如果换成其他校区是不是F_STATE也要修改。
F_STATE存在的目的尚不清楚，我尝试修改提交的数据，将直接提交的p1_ZaiXiao等字段与F_STATE里的p1_ZaiXiao等字段不一致，前者为宝山，后者为延长，上报的结果是宝山。似乎F_STATE里的数据并不会影响直接post的数据，但是F_STATE置空又会提示地址不完整，可能服务器只会校验F_STATE里的某个数据，具体是哪个没试出来。

>不过话说这每日两报还管你在哪个校区吗？
因为我本人在延长所以还是上报在所在校区比较好…其实直接改也不是很麻烦

**Comment by BlueFisher** [comment]
@panghaibin 好的，有空我增加这个功能

**Comment by CabbageSong** [comment]
> F_state是将json格式的要上报的信息base64 encode后得到的，base64 decode后可查看原始数据，包含了日期，体温，地址等信息，最好每次上报时都重新base64 encode生成

同意 @panghaibin 每次上报都重新生成F_state的说法，不过我也还没实验出F_state生成的方法，感谢 @panghaibin 提供思路！

> 因为我本人在延长所以还是上报在所在校区比较好…其实直接改也不是很麻烦

我也是在延长，同需要这个功能，感谢作者 @BlueFisher 的辛勤付出！

**Comment by BlueFisher** [comment]
@panghaibin @CabbageSong 已增加 https://github.com/BlueFisher/SHU-selfreport/commit/e4f36a8c40ccfa93fd2b22f43dfb6608e7f50497
F_STATE目前测试下来不需要修改，不影响提交结果

**Comment by Holaplace** [comment]
在提交的 pull requests 中，我添加了 F_STATE 生成模块，主要机制为将其加密之后，对提交的前端控件状态进行修改。目前只有表单提交时间需要修改，其他暂时没有发现有需要。

F_STATE 为FineUI提供的表单验证机制，以防后续升级后台验证机制，使得本项目提交的表单无效。参考地址为：https://pro.fineui.com/#/form/form_compare.aspx

**Comment by BlueFisher** [comment]
@Holaplace Merged https://github.com/BlueFisher/SHU-selfreport/commit/5c2da2b0d6fe2cc51c807c2032e8d81436f2d164

**Comment by CabbageSong** [comment]
感谢各位大佬
