### ISSUE TITLE
不能正常运行

### ISSUE THREAD

**Issue by bear-zd** [BlueFisher/SHU-selfreport#14]
在填写账号密码之后，登陆成功之后弹出异常的输出(main.py第85行)
```python
sess.get('https://newsso.shu.edu.cn/oauth/authorize?response_type=code&client_id=WUHWfrntnWYHZfzQ5QvXUCVy&redirect_uri=https%3a%2f%2fselfreport.shu.edu.cn%2fLoginSSO.aspx%3fReturnUrl%3d%252fDefault.aspx&scope=1')
```

**Comment by BlueFisher** [comment]
正在处理中...

**Comment by BlueFisher** [comment]
登陆系统改动了，暂时没有办法通过requests来模拟chrome中的登录，不知道哪里有限制，有大佬能成功登录吗

**Comment by Lanszhang131** [comment]
很奇怪，我用树莓派和iPhone跑程序就可以登录，但是用电脑就不行

**Comment by Lanszhang131** [comment]
![image](https://user-images.githubusercontent.com/50519601/101980952-1e902b80-3ca4-11eb-8586-ddc0c53b3c89.png)
会是这个多出来的parameter搞的鬼吗

**Comment by Lanszhang131** [comment]
问题已解决！！可以在访问selfreport.shu.edu.cn返回的网址中取到这个state，然后再访问图中这个url的时候把parameter的state改成取到的state即可！

**Comment by BlueFisher** [comment]
@Lanszhang131 我尝试了一下还是不行，你把你的代码pull request一下？

**Comment by Lanszhang131** [comment]
不好意思我之前没有fork你的代码，之前每日一报是自己写的，你试试看这样改？我就是类似这样写的然后成功了
sess = requests.Session()
try:
        r = sess.get('https://selfreport.shu.edu.cn/')
        code = r.url.split('/')[-1] 
        url_param = eval(base64.b64decode(code).decode("utf-8"))
        state = url_param['state']

        sess.post(r.url, data={
            'username': username,
            'password': password,
            'login_submit': ''
        }, )
        sess.get(f"https://newsso.shu.edu.cn/oauth/authorize?client_id=WUHWfrntnWYHZfzQ5QvXUCVy&response_type=code&scope=1&redirect_uri=https%3A%2F%2Fselfreport.shu.edu.cn%2FLoginSSO.aspx%3FReturnUrl%3D%252f&state={state}")
except Exception as e:
        print(e,'\n')

**Comment by Lanszhang131** [comment]
不好意思我之前没folk你的代码，不太熟悉你代码里的模块，我按照自己的代码在你的代码的登录模块上改了一下，你看一下吧
```
import base64
def login(username, password):
    sess = requests.Session()
    while True:
        try:
            r = sess.get('https://selfreport.shu.edu.cn')
            code = r.url.split('/')[-1]
            url_param = eval(base64.b64decode(code).decode("utf-8"))
            state = url_param['state']

            sess.post(r.url, data={
                'username': username,
                'password': password
            })
            sess.get(f"https://newsso.shu.edu.cn/oauth/authorize?client_id=WUHWfrntnWYHZfzQ5QvXUCVy&response_type=code&scope=1&redirect_uri=https%3A%2F%2Fselfreport.shu.edu.cn%2FLoginSSO.aspx%3FReturnUrl%3D%252f&state={state}")
        except Exception as e:
            print(e)
            continue
        break
```

**Comment by BlueFisher** [comment]
OK，已修复https://github.com/BlueFisher/SHU-selfreport/commit/1ee5811207f9191d0d20d54d201f3500576ac897
十分感谢

**Comment by Holaplace** [comment]
@BlueFisher config.yaml里面的账号密码可以用啊。是泄露了吗？如果是，还是赶快删除吧

**Comment by BlueFisher** [comment]
傻逼了傻逼了...

**Comment by MJT-Arthas** [comment]
目前我是用js写的一个后台，然后前端用了微信小程序一键填报。但是js在获取cookie时候遇到了问题，目前采用的还是模拟表单填写的傻瓜方式，不知道能否交流一下？

**Comment by BlueFisher** [comment]
@MJT-Arthas nodejs里应该也有像python requests一样的包吧，基本都差不多的，发送http请求就行了

**Comment by MJT-Arthas** [comment]
我是环化的 我的V 787408654 希望拥有个好友位
