### ISSUE TITLE
体温变0

### ISSUE THREAD

**Issue by EdmundZarek** [BlueFisher/SHU-selfreport#16]
1.16早报开始体温变为0

**Comment by BlueFisher** [comment]
服务器的问题吧应该

**Comment by EdmundZarek** [comment]
身边的几个朋友都是这样的，从昨天开始体温变成0填上去的 都是通过workflow设置好就没管过 大佬有木有解决方法 万分感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BlueFisher/SHU-selfreport"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月17日(星期天) 晚上9:29
收件人:&nbsp;"BlueFisher/SHU-selfreport"<SHU-selfreport@noreply.github.com&gt;;
抄送:&nbsp;"　周志鹏"<1915503431@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [BlueFisher/SHU-selfreport] 体温变0 (#16)





 
服务器的问题吧应该

**Comment by BlueFisher** [comment]
前端传的就是37，是服务器的问题，这个没法解决，也不需要解决

**Comment by EdmundZarek** [comment]
了解，感谢解答

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BlueFisher/SHU-selfreport"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月17日(星期天) 晚上9:40
收件人:&nbsp;"BlueFisher/SHU-selfreport"<SHU-selfreport@noreply.github.com&gt;;
抄送:&nbsp;"　周志鹏"<1915503431@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [BlueFisher/SHU-selfreport] 体温变0 (#16)





 
前端传的就是37，是服务器的问题，这个没法解决，也不需要解决
