### ISSUE TITLE
关于回家之后的每日两报

### ISSUE THREAD

**Issue by DMax1314** [BlueFisher/SHU-selfreport#17]
回家之后每日两报就要添加个人地址了，一个人还好，但是要给一个宿舍报这种就比较麻烦了emm

**Comment by BlueFisher** [comment]
后续再看如何修改代码，目前也无所谓你填的地址是不是真的地址

**Comment by Chenchen2001** [comment]
离校换成了“每日一报”之后要填报的东西变了蛮多的qwq

**Comment by BlueFisher** [comment]
我现在还没离校，暂时看不到离校后的填报内容

**Comment by helijiqunQAQ** [comment]
同求离校后的代码更新~
离校后不需要填体温了，但是地址什么的每个人填的都不一样了

**Comment by BlueFisher** [comment]
下周争取借个已经离校的账号再更新

**Comment by Lanszhang131** [comment]
我正在写每日一报的更新，主要思想是从每个人的离校申请取到每个人的省市详细地址，目前这块已经成功了，但是f_state貌似有一块内容会取不到，正在解决中。。。

**Comment by zhujiayi2** [comment]
![IMG_169](https://user-images.githubusercontent.com/67741727/105621078-cd488f80-5e3e-11eb-98db-acd9a7dc83a6.jpeg)
现在是变成这样了，最麻烦的还是国内详细地址...

**Comment by BlueFisher** [comment]
问题不大，地址可以写在配置文件里或者用github的settings里的environment设置环境变量

**Comment by biqigubafan1** [comment]
加油(手动滑稽）

**Comment by panghaibin** [comment]
我有个想法，每次填报时先获取上次填报所用的地址，作为本次填报的地址，这样可以程序只需存储学号和密码即可，不用为每个人单独配置地址；而若用户手动更新了地址（毕竟寒假去往另一个地方也是很常见的），程序也能够自动填报新的地址。

**Comment by BlueFisher** [comment]
已更新，兼容每日一报/每日两报
但目前暂时不支持配置地址，现在是随机地址
https://github.com/BlueFisher/SHU-selfreport/commit/910878c8e114803663bb02bf1500b645c3ec4218

**Comment by helijiqunQAQ** [comment]
非上海怎么改地址？直接改代码好像不行

**Comment by BlueFisher** [comment]
暂时不支持改地址

**Comment by Lanszhang131** [comment]
这是我写[自动上报代码](https://github.com/Lanszhang131/DailyReport_SHU)，加入了自动识别一报和两报还有自动取地址，当然前提条件是一定要自己手动上报过一报，另外解决了上海和外地上报内容不同的问题，大家可以参考一下！
