### ISSUE TITLE
报送地址出现乱码

### ISSUE THREAD

**Issue by wllshdx** [BlueFisher/SHU-selfreport#24]
昨日pull了项目，发现“详细地址”为乱码。
![微信图片_20210130105556](https://user-images.githubusercontent.com/43229824/106345277-f4dda300-62e9-11eb-9ba4-3b9f165e05d6.jpg)

**Comment by BlueFisher** [comment]
这个不是乱码，就是随机生成的一个地址。原来版本每天是随机地址，但是最新版本会根据你前一天的地址重复报，你要在前一天的晚上7点自动报完后去健康之路上手动改真实的信息，当然你不改也行，那就一直是这个地址。
