### ISSUE TITLE
28日起提交失败

### ISSUE THREAD

**Issue by akhialomgir** [BlueFisher/SHU-selfreport#25]
2021-01-30 20:12:38.305442 每日一报提交失败
﻿if(!F.f_viewState(__VIEWSTATE,'0n44NIehraitRR59aKy1P+t3DCEEorjiplghHUu/jIGXB8VRsDHFU1BCN4ODynUhYyteIaUR+zdx04LVTuXl/taHenn/s7yjGXAh0GaTmqVF5n4+flvAjSN80EhxSxVRo91oNf50rh53Yp1vAmyXWU68Lm6P/QfQzT1VUn2B/LnWLcBTdiPH0StnXFYgfGtY9uKN7393bP2OXCnSDfSjdWZcz9Dltm0VCR08NPp9Xek9qxU1vG7g3wu3O0YSnCy/59lwz73Clb6fJnS5sbn4tyF7hL8u+6vUM8XwsSN1KMbMVOjSVRBHmzgAHdgZI2zex5h32FsAQT2EmPmCKsV7Ina8RYSwgd+QhshW+N5eQJiuDG+BkS4OHhb0xcLE73ljavFAQs0VBrbptm40GIDWJNcPXuWWC0xE8Z6DUB+j3XaccpXt1o7S4vvaSnETKF98/sW0pJ/VOHpKH4Oy6j4Da+mcM7p9xI44oaS+6GHqMkR9BjY6N+sRWhxtbyocYRJggEQpxDLC3HX3tjuo0GDTrO+V9ASIvGHo81L81wyM/FMl++cq6kD1fzKNeI7KLlqOcY8FwptGDRpzVEuzAHaXNcw9J9sfGu4PHlissjwdxpARTG063VUhH+OS2eimn61IwBMkbl7VhrWXfGBpJwHvU+JnDN8a0Uv/7N0JG+s6QSGH44qXlZcPAYuSZhjjqQ594h0r7FdWOArpvYUv1/c2FYMGF/SMvp8ihfZvbwwDWPxxWAKAx/nt+aQYKg6YJ05iV56xquyNd6LvwtLb4+i7xhwSKFPm2SrDuxcVK2CS2veuKppXU1A6tqpJX8/FYj1KYlm22FnfFufXHeRbWgpc7Pc4BHh4hbjpfrPaYgHWyMKHPC/SIn/L6bcUQ2ym8bgZuuBhMk1AapJVVaAm41PBwEeQuCIlA7osh+U2SnWCo1fbcSWoDp2b5TvzXR94GfA36R6s808JO2HZUzp8fo0EU797fKFp1jlLayR2HaKVtydTUMf5DXJXJMVfVuKs87j6MrjL3ogtYnGPze2t2tXn4CaxT79Jpl+3I8vSVEpuIFUW6kJWSb6byOoIyL+5Jic7',0,344))return;;;var f0=F('p1_ContentPanel1_ZhongGFXDQ'),f1=F('p1_DaoXQLYGJ'),f2=F('p1_DaoXQLYCS');F.f_state(f2,{"Text":"没有"});

**Comment by BlueFisher** [comment]
建议使用最新版本的程序，另从错误信息看你有10天没有每日一报了？

**Comment by akhialomgir** [comment]
> 
> 
> 建议使用最新版本的程序，另从错误信息看你有10天没有每日一报了？

已经更新了的，其实就三天

**Comment by akhialomgir** [comment]
不过在手动报了之后就好了，大概是因为新的表单？
