### ISSUE TITLE
就餐字段只能选中最后一个

### ISSUE THREAD

**Issue by Holaplace** [BlueFisher/SHU-selfreport#3]
main.py 行71-73 post相同字段时只能选中最后一项，建议修改成：
 'p1$ShiFJC': ['早餐', '午餐', '晚餐'],

**Comment by BlueFisher** [comment]
感谢，已提交 [https://github.com/BlueFisher/SHU-selfreport/commit/7504e45e281d27c4b039ac12c869860a9de5e52f](https://github.com/BlueFisher/SHU-selfreport/commit/7504e45e281d27c4b039ac12c869860a9de5e52f)
