### ISSUE TITLE
21-11-04变更

### ISSUE THREAD

**Issue by hwh820** [BlueFisher/SHU-selfreport#51]
fstate_generator.py 
第55行
#    ShiFSH = '是'
    ShiFSH = '在上海（校内）'
fstate_day.json
1671行，变更主体：p1_ShiFSH
 "p1_ShiFSH": {
        "Hidden": false,
        "F_Items": [
            [
                "在上海（校内）",
                "在上海（校内）",
                1
            ],
            [
                "在上海（不在校内）",
                "在上海（不在校内）",
                1
            ],
            [
                "不在上海",
                "不在上海",
                1
            ]
        ],
        "SelectedValue": "在上海（校内）"
    },

**Comment by BlueFisher** [comment]
https://github.com/BlueFisher/SHU-selfreport/commit/6da0e054d5902147fb4a23a30db8118e50a65856
