### ISSUE TITLE
是不是只能报在学校的？

### ISSUE THREAD

**Issue by tty827426358** [BlueFisher/SHU-selfreport#58]
是不是只能报在学校的？我回家了，然后填报也改成了在家，但是一直填报失败。
Run python -u main.py
=====0256=====
第0次尝试登陆
登录成功
HTTPSConnectionPool(host='selfreport.shu.edu.cn', port=443): Max retries exceeded with url: /DayReportNotice.aspx (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2240c6c670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
notice 失败，已忽略
HTTPSConnectionPool(host='selfreport.shu.edu.cn', port=443): Max retries exceeded with url: /MyMessages.aspx (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2240c6ca30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
view_messages 失败，已忽略
第0次尝试填报
#正在获取手机号...
#正在获取前一天的填报信息...
承诺
答题
是否在上海
是否家庭地址
已提交随申码
已提交行程码
2022-01-22 10:01:57.355598 每日一报提交成功
=====1555=====
第0次尝试登陆
登录成功
HTTPSConnectionPool(host='selfreport.shu.edu.cn', port=443): Max retries exceeded with url: /DayReportNotice.aspx (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f224117bf70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
notice 失败，已忽略
HTTPSConnectionPool(host='selfreport.shu.edu.cn', port=443): Max retries exceeded with url: /MyMessages.aspx (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2240c6cfd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
view_messages 失败，已忽略
第0次尝试填报
#正在获取手机号...
#正在获取前一天的填报信息...
承诺
答题
是否在上海
是否家庭地址
未检测到已提交随申码
oyIcIIHUYDw=
未检测到已提交行程码
Fq8mxSEqbTM=
2022-01-22 10:08:44.911568 每日一报提交成功
=====0134=====
第0次尝试登陆
登录成功
HTTPSConnectionPool(host='selfreport.shu.edu.cn', port=443): Max retries exceeded with url: /DayReportNotice.aspx (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2240cda130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
notice 失败，已忽略
HTTPSConnectionPool(host='selfreport.shu.edu.cn', port=443): Max retries exceeded with url: /MyMessages.aspx (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2240b2d2b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
view_messages 失败，已忽略
第0次尝试填报
#正在获取手机号...
#正在获取前一天的填报信息...
承诺
答题
是否在上海
是否家庭地址
未检测到已提交随申码
IBZmJBWe2Qo=
未检测到已提交行程码

提示对话框
请上传行程码图片
 确定
2022-01-22 10:15:36.555649 每日一报提交失败
=====0147=====
第0次尝试登陆
登录成功
第0次尝试填报
#正在获取手机号...
#正在获取前一天的填报信息...
承诺
答题
是否在上海
是否家庭地址
未检测到已提交随申码

未检测到已提交行程码
wLxQgltuBdw=
2022-01-22 10:18:09.891651 每日一报提交成功
[0256, 1555, 0147] 每日一报提交成功，[0134] 每日一报提交失败，查看日志获取详情
Error: Process completed with exit code 1.

**Comment by XiGuang** [comment]
是否上海的那段好像有点问题，直接注释掉应该就可以用了

**Comment by BlueFisher** [comment]
应该是不影响，这个看起来是行程码上传失败，导致没有最终提交成功。后面需要进一步判断行程码是否上传成功

**Comment by tty827426358** [comment]
我不知道呀，回家之后我也重新上传了健康码、行程码的。“上海那段好像有点问题，直接注释掉”是什么意思，我文科生不太懂呢
Run python -u main.py
  python -u main.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.12/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.12/x64/lib
    users: ***
=====0333=====
第0次尝试登陆
登录成功
第0次尝试填报
#正在获取手机号...
#正在获取前一天的填报信息...
承诺
答题
是否在上海
是否家庭地址
已提交随申码
已提交行程码
提示对话框
请正确填写当天是否在上海及当天所在省市
 确定
2022-01-23 10:56:03.586734 每日一报提交失败
[] 每日一报提交成功，[0333] 每日一报提交失败，查看日志获取详情
Error: Process completed with exit code 1.

**Comment by BlueFisher** [comment]
更新最新的commit试试：https://github.com/BlueFisher/SHU-selfreport/commit/6bad7696493dcde47864db92d5ca17ed5850d2d4

**Comment by tty827426358** [comment]
okkk搞定了，感谢大哥，您是好人！
