### ISSUE TITLE
服务器上运行报错

### ISSUE THREAD

**Issue by Picasun** [BlueFisher/SHU-selfreport#66]
Traceback (most recent call last):
  File "main.py", line 305, in <module>
    s = Service()
TypeError: __init__() missing 1 required positional argument: 'executable_path'

**Comment by BlueFisher** [comment]
更新 selenium，并手动将 chrome driver 的路径设置为环境变量，或在 `Service()` 里增加 `executable_path` 参数手动指定chrome driver 的路径

**Comment by eldoradoel** [comment]
我是debian 运行apt install ruby-chromedriver-helper即可
