### ISSUE TITLE
连接VPN失败，如何解决？

### ISSUE THREAD

**Issue by ghy861918226** [BlueFisher/SHU-selfreport#71]
Run kota65535/github-openvpn-connect-action@v1
========== begin configuration ==========
client
dev tun
proto tcp

<connection>
remote openvpn3.shu.edu.cn 443
</connection>

comp-lzo
resolv-retry infinite
nobind
persist-key
persist-tun
setenv CLIENT_CERT 0
auth-user-pass
remote-cert-tls server
verb 3

sndbuf 0
rcvbuf 0
mssfix 0
cipher none

<ca>
-----BEGIN CERTIFICATE-----
MIIEoTCCA4mgAwIBAgIJAMW52H83M9JAMA0GCSqGSIb3DQEBCwUAMIGRMQswCQYD
VQQGEwJDTjELMAkGA1UECBMCU0gxETAPBgNVBAcTCFNoYW5nSGFpMQwwCgYDVQQK
EwNTSFUxDDAKBgNVBAsTA1NIVTEPMA0GA1UEAxMGU0hVIENBMRAwDgYDVQQpEwdF
YXN5UlNBMSMwIQYJKoZIhvcNAQkBFhRyb2RkeTE5ODZAc2h1LmVkdS5jbjAeFw0x
NzA2MjEwOTQwMjlaFw0yNzA2MTkwOTQwMjlaMIGRMQswCQYDVQQGEwJDTjELMAkG
A1UECBMCU0gxETAPBgNVBAcTCFNoYW5nSGFpMQwwCgYDVQQKEwNTSFUxDDAKBgNV
BAsTA1NIVTEPMA0GA1UEAxMGU0hVIENBMRAwDgYDVQQpEwdFYXN5UlNBMSMwIQYJ
KoZIhvcNAQkBFhRyb2RkeTE5ODZAc2h1LmVkdS5jbjCCASIwDQYJKoZIhvcNAQEB
BQADggEPADCCAQoCggEBAJ17qOLBJgX7DKsBxVhqpfYkZcPwy8DggDiwRHNLLP3h
aEWRcS5NViqGthWh4mWvVkD9RypYlUywbYewoSkuLyllsFuw+iZUR93cWGMjccq/
9ZdhVPpYCGRJrtkTNeVtU9XTXEjZ3vWEwAMpOcVdhLQz6kxCVTt2qrB4ClhIAdPh
jaz5tusNlwVGzaM7EMIr3O08Y8gYlAe78tkD+18uCMYIyKPORs9H31UHbreLcONv
4Lc3dOz/g4KOQTkuwqcRnTJN1AVVfpjFUQeabyxFV/u4BkSvU33HWxLzYiyDGZkU
W8PLr1mouNEXWGHxfhooZb9wozk+jfuLYk3KhKh9+ZMCAwEAAaOB+TCB9jAdBgNV
HQ4EFgQU2sjeWJZf5o/1eL1Ke5PyE7K1nw4wgcYGA1UdIwSBvjCBu4AU2sjeWJZf
5o/1eL1Ke5PyE7K1nw6hgZekgZQwgZExCzAJBgNVBAYTAkNOMQswCQYDVQQIEwJT
SDERMA8GA1UEBxMIU2hhbmdIYWkxDDAKBgNVBAoTA1NIVTEMMAoGA1UECxMDU0hV
MQ8wDQYDVQQDEwZTSFUgQ0ExEDAOBgNVBCkTB0Vhc3lSU0ExIzAhBgkqhkiG9w0B
CQEWFHJvZGR5MTk4NkBzaHUuZWR1LmNuggkAxbnYfzcz0kAwDAYDVR0TBAUwAwEB
/zANBgkqhkiG9w0BAQsFAAOCAQEATqu24naX9L6jyzXt+mBJAS5IWr7gfh5Ymi7X
Tl+uSXS+H0w7VYqSGsrQsd17U9RfcAxglhGx2FtYvuYVWHQ4InaUjbrzxDrFO+ZG
rN471ASybovHR97rHfPOnqigAbDaKLynb8JoFYkzAxRAclPh/jZFXpG06KC+fkW/
ox+1WKF/6d5gXOZOTf0GuJi4JHRojDzb5p/Z6/8gxE9krVsQmfiR3HnaegyTVMle
KzpCQRuEx5rn/uDvV6joYCwy4q0BkQTKGBeUofR2ETlTeC7t6l+GKRPwCQ8BeBvL
e0+RSP6QWl/+flS0qdmtSswuZF98OqAuu6wW2PHXB3auUn77nw==
-----END CERTIFICATE-----
</ca>
# ----- modified by action -----
auth-user-pass up.txt

=========== end configuration ===========
running command: sudo openvpn --config .github/vpn/config.ovpn --daemon --log openvpn.log --writepid openvpn.pid
Fri Mar [11](https://github.com/ghy861918226/SHU-selfreport/runs/5505920772?check_suite_focus=true#step:8:11) 03:23:31 2022 Option 'nobind' in .github/vpn/config.ovpn:9 is ignored by previous <connection> blocks 
Fri Mar 11 03:23:31 2022 Option 'mssfix' in .github/vpn/config.ovpn:19 is ignored by previous <connection> blocks 

Fri Mar 11 03:23:31 2022 WARNING: file 'up.txt' is group or others accessible
Fri Mar 11 03:23:31 2022 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 19 2021
Fri Mar 11 03:23:31 2022 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10
Fri Mar 11 03:23:31 2022 ******* WARNING *******: '--cipher none' was specified. This means NO encryption will be performed and tunnelled data WILL be transmitted in clear text over the network! PLEASE DO RECONSIDER THIS SETTING!
Fri Mar 11 03:23:31 2022 TCP/UDP: Preserving recently used remote address: [AF_INET]202.[12](https://github.com/ghy861918226/SHU-selfreport/runs/5505920772?check_suite_focus=true#step:8:12)0.127.112:443
Fri Mar 11 03:23:31 2022 Socket Buffers: R=[[13](https://github.com/ghy861918226/SHU-selfreport/runs/5505920772?check_suite_focus=true#step:8:13)1072->131072] S=[[16](https://github.com/ghy861918226/SHU-selfreport/runs/5505920772?check_suite_focus=true#step:8:16)384->16384]
Fri Mar 11 03:23:31 2022 Attempting to establish TCP connection with [AF_INET]202.120.127.112:443 [nonblock]
Fri Mar 11 03:23:32 2022 TCP connection established with [AF_INET]202.120.127.112:443
Fri Mar 11 03:23:32 2022 TCP_CLIENT link local: (not bound)
Fri Mar 11 03:23:32 2022 TCP_CLIENT link remote: [AF_INET]202.120.127.112:443
Fri Mar 11 03:23:33 2022 TLS: Initial packet from [AF_INET]202.120.127.112:443, sid=c9f97735 6286fa42
Fri Mar 11 03:23:33 2022 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Fri Mar 11 03:23:33 2022 VERIFY OK: depth=1, C=CN, ST=SH, L=ShangHai, O=SHU, OU=SHU, CN=SHU CA, name=EasyRSA, emailAddress=roddy[19](https://github.com/ghy861918226/SHU-selfreport/runs/5505920772?check_suite_focus=true#step:8:19)86@shu.edu.cn
Fri Mar 11 03:23:33 [20](https://github.com/ghy861918226/SHU-selfreport/runs/5505920772?check_suite_focus=true#step:8:20)[22](https://github.com/ghy861918226/SHU-selfreport/runs/5505920772?check_suite_focus=true#step:8:22) VERIFY KU OK
Fri Mar 11 03:[23](https://github.com/ghy861918226/SHU-selfreport/runs/5505920772?check_suite_focus=true#step:8:23):33 2022 Validating certificate extended key usage
Fri Mar 11 03:23:33 2022 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Fri Mar 11 03:23:33 2022 VERIFY EKU OK
Fri Mar 11 03:23:33 2022 VERIFY OK: depth=0, C=CN, ST=SH, L=ShangHai, O=SHU, OU=SHU, CN=server, name=EasyRSA, emailAddress=roddy1986@shu.edu.cn
Fri Mar 11 03:23:34 2022 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES[25](https://github.com/ghy861918226/SHU-selfreport/runs/5505920772?check_suite_focus=true#step:8:25)6-GCM-SHA384, 2048 bit RSA
Fri Mar 11 03:23:34 2022 [server] Peer Connection Initiated with [AF_INET]202.120.1[27](https://github.com/ghy861918226/SHU-selfreport/runs/5505920772?check_suite_focus=true#step:8:27).112:443
Fri Mar 11 03:23:[35](https://github.com/ghy861918226/SHU-selfreport/runs/5505920772?check_suite_focus=true#step:8:35) 2022 SENT CONTROL [server]: 'PUSH_REQUEST' (status=1)
Fri Mar 11 03:23:[36](https://github.com/ghy861918226/SHU-selfreport/runs/5505920772?check_suite_focus=true#step:8:36) 2022 AUTH: Received control message: AUTH_FAILED
Fri Mar 11 03:23:36 2022 SIGTERM[soft,auth-failure] received, process exiting
Error: VPN connection failed.

**Comment by panghaibin** [comment]
请确认存储的Secret学号和密码是否正确。我注意到你的Actions输出登录每日一报系统也失败，可能你没有设置对学号和密码

**Comment by ghy861918226** [comment]
好的，我再检查一下
