### ISSUE TITLE
服务器无法登陆

### ISSUE THREAD

**Issue by zhujiayi2** [BlueFisher/SHU-selfreport#74]
服务器使用最新的脚本出现无法登陆到ssl的错误
用户名和密码检查无误且使用浏览器可以正常登录填报
<img width="984" alt="image" src="https://user-images.githubusercontent.com/67741727/159223116-4138fcb1-58b2-4ad1-b717-d81a64be1d0b.png">

**Comment by BlueFisher** [comment]
是不是代理的问题？

**Comment by zhujiayi2** [comment]
不是吧 这台服务器没配置过任何代理诶
