### ISSUE TITLE
设立一个海外版吧

### ISSUE THREAD

**Issue by amseram** [BlueFisher/SHU-selfreport#77]
为海外的孩子搞个海外版吧，现在只能用selenium自动完成

**Comment by BlueFisher** [comment]
selenium能完成的rquests也能完成啊应该

**Comment by panghaibin** [comment]
运行环境是什么？可以把报错直接贴上来

**Comment by amseram** [comment]
已经改好了.....改了要提交的内容...替换了fstate

选择国外的好多信息是没有的
原来的报错：
=====0252=====
登录成功
#正在获取历史信息...#
#正在获取个人信息...
-ShouJHM-
#正在获取前一天的填报信息...
-ShiFSH-
获取前一天日报有错误 f7=new F.CheckBox({f_state:f7_state,id:'ctl03_GuoNei',name:'ctl03$GuoNei',cls:'mycheckbox',fieldLabel:'当天是否在国内',readonly:true,displayType:'switch',switchTextVisible:true,switchOnText:'国内',switchOffText:'国外',checked:false,inputValue:'ctl03_GuoNei'}) f8=new F.Label({f_state:{},id:'ctl03_ShiFSH',name:'ctl03$ShiFSH',hidden:true,fieldLabel:'当天是否在上海',value:''})
-ShiFZX-
None
-XiaoQu-
获取前一天日报有错误 f9=new F.RadioButtonList({f_state:f9_state,id:'ctl03_ShiFZX',name:'ctl03$ShiFZX',hidden:true,fieldLabel:'当天是否住学校',readonly:true,required:true,columnNumber:2,value:f9_state.SelectedValue,data:f9_state.F_Items}) f10=new F.Label({f_state:{},id:'ctl03_XiaoQu',name:'ctl03$XiaoQu',hidden:true,fieldLabel:'所在校区',value:''})
-ddlSheng-
获取前一天日报有错误 f13_state={"Hidden":true,"F_Items":[],"SelectedValueArray":[]} f13=new F.DropDownList({f_state:f13_state,id:'ctl03_ddlSheng',name:'ctl03$ddlSheng',hidden:true,fieldLabel:'当天所在省',readonly:true,compareValue:'-1',compareOperator:'!=',compareMessage:'请选择省份！',hiddenName:'ctl03$ddlSheng$Value',data:f13_state.F_Items})
-ddlShi-
获取前一天日报有错误 f14_state={"Hidden":true,"F_Items":[],"SelectedValueArray":[]} f14=new F.DropDownList({f_state:f14_state,id:'ctl03_ddlShi',name:'ctl03$ddlShi',hidden:true,fieldLabel:'当天所在市',readonly:true,compareValue:'-1',compareOperator:'!=',compareMessage:'请选择市！',hiddenName:'ctl03$ddlShi$Value',data:f14_state.F_Items})
-ddlXian-
获取前一天日报有错误 f15_state={"Hidden":true,"F_Items":[],"SelectedValueArray":[]} f15=new F.DropDownList({f_state:f15_state,id:'ctl03_ddlXian',name:'ctl03$ddlXian',hidden:true,fieldLabel:'当天所在县区',readonly:true,compareValue:'-1',compareOperator:'!=',compareMessage:'请选择县区！',hiddenName:'ctl03$ddlXian$Value',data:f15_state.F_Items})
-XiangXDZ-
###无
-ShiFZJ-
否

**Comment by panghaibin** [comment]
原来在海外也要填shu的每日一报么😂，一直默认用户是在国内的

如果您修改适配好了的话，可以考虑维护一个fork，或者提pr
