### ISSUE TITLE
建议把填报时间改成一定时间内随机

### ISSUE THREAD

**Issue by EdmundZarek** [BlueFisher/SHU-selfreport#78]
一是学校vpn本来就辣鸡连不了太多人 有的人就会填报失败 二是免得他查到同一时间大量填报

**Comment by BlueFisher** [comment]
已修改，https://github.com/BlueFisher/SHU-selfreport/commit/57b2d4676e43f8905f6715a8e7db82b1b8294c5b#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R18  
看最近几天的情况
