### ISSUE TITLE
在上海回家后填报不上

### ISSUE THREAD

**Issue by helijiqunQAQ** [BlueFisher/SHU-selfreport#79]
前一天是完整填报的，但当天获取前一天报送内容会报错，我看了下所有在校的都能报上，回家了的都出错了

报错内容：
#正在获取前一天的填报信息...
-ShiFSH-
获取前一天日报有错误 f7=new F.CheckBox({f_state:{},id:'ctl03_GuoNei',name:'ctl03$GuoNei',cls:'mycheckbox',fieldLabel:'当天是否在国内',readonly:true,displayType:'switch',switchTextVisible:true,switchOnText:'国内',switchOffText:'国外',checked:true,inputValue:'ctl03_GuoNei'}) f8=new F.Label({f_state:{},id:'ctl03_ShiFSH',name:'ctl03$ShiFSH',hidden:true,fieldLabel:'当天是否在上海',value:''})
-ShiFZX-
None
-XiaoQu-
获取前一天日报有错误 f9=new F.RadioButtonList({f_state:f9_state,id:'ctl03_ShiFZX',name:'ctl03$ShiFZX',hidden:true,fieldLabel:'当天是否住学校',readonly:true,required:true,columnNumber:2,value:f9_state.SelectedValue,data:f9_state.F_Items}) f10=new F.Label({f_state:{},id:'ctl03_XiaoQu',name:'ctl03$XiaoQu',hidden:true,fieldLabel:'所在校区',value:''})
-ddlSheng-
获取前一天日报有错误 f13_state={"F_Items":[],"SelectedValueArray":[]} f13=new F.DropDownList({f_state:f13_state,id:'ctl03_ddlSheng',name:'ctl03$ddlSheng',fieldLabel:'当天所在省',readonly:true,compareValue:'-1',compareOperator:'!=',compareMessage:'请选择省份！',hiddenName:'ctl03$ddlSheng$Value',data:f13_state.F_Items})
-ddlShi-
获取前一天日报有错误 f14_state={"F_Items":[],"SelectedValueArray":[]} f14=new F.DropDownList({f_state:f14_state,id:'ctl03_ddlShi',name:'ctl03$ddlShi',fieldLabel:'当天所在市',readonly:true,compareValue:'-1',compareOperator:'!=',compareMessage:'请选择市！',hiddenName:'ctl03$ddlShi$Value',data:f14_state.F_Items})
-ddlXian-
获取前一天日报有错误 f15_state={"F_Items":[],"SelectedValueArray":[]} f15=new F.DropDownList({f_state:f15_state,id:'ctl03_ddlXian',name:'ctl03$ddlXian',fieldLabel:'当天所在县区',readonly:true,compareValue:'-1',compareOperator:'!=',compareMessage:'请选择县区！',hiddenName:'ctl03$ddlXian$Value',data:f15_state.F_Items})
-XiangXDZ-
获取前一天日报有错误 f15=new F.DropDownList({f_state:f15_state,id:'ctl03_ddlXian',name:'ctl03$ddlXian',fieldLabel:'当天所在县区',readonly:true,compareValue:'-1',compareOperator:'!=',compareMessage:'请选择县区！',hiddenName:'ctl03$ddlXian$Value',data:f15_state.F_Items}) f16=new F.TextBox({f_state:{},id:'ctl03_XiangXDZ',name:'ctl03$XiangXDZ',blockMD:6,fieldLabel:'详细地址',readonly:true})

**Comment by YohannWan1** [comment]
同为上海人，这几天也填报不上

**Comment by BlueFisher** [comment]
不在校的要提交随申码行程码，但本脚本不提供虚假信息😄 https://github.com/BlueFisher/SHU-selfreport/blob/master/main.py#L72。
其他的信息问题还需要排查
