### ISSUE TITLE
随申码

### ISSUE THREAD

**Issue by zhujiayi2** [BlueFisher/SHU-selfreport#80]
学校是否增加了随申码检测？
目前脚本使用行程码代替随申码，但在运行时会出现“请提交随申码”的错误
能否和行程码一样通过图片和动态时间的方式绕过？
![4](https://user-images.githubusercontent.com/67741727/160269411-0acfa86d-c1d5-4b69-bacd-cb78c464fe62.PNG)

**Comment by BlueFisher** [comment]
现在随申码和行程码都不自动填报，因为我们不能提供虚假的信息😄 https://github.com/BlueFisher/SHU-selfreport/blob/master/main.py#L72

**Comment by panghaibin** [comment]
~~显然，在自己的repo把那个71行删除就可以正常使用了~~
~~打个小广告：~~  [shuasr](https://github.com/panghaibin/shuasr)

**Comment by zhujiayi2** [comment]
谢谢啦，我去试试卷网模式hh
